### ISSUE TITLE
Detected as a Trojan by Windows Defender

### ISSUE THREAD

**Issue by simon-dmsn** [aneeskhan47/hypervisorcontrol#1]
Cool project but detected as a Trojan by Windows...
Can you do something to improve ?
Thanks !

**Comment by aneeskhan47** [comment]
@simon-dmsn It does not contain any malware or virus. it's just a false positive by Windows Defender.

It's actually a Powershell script I converted it to exe. you can view the source code of it here:

https://github.com/aneeskhan47/hypervisorcontrol/blob/main/HypervisorControl.ps1

or you can directly download the `HypervisorControl.ps1` file and run it as administrator.
